import type { MediaType } from "@/lib/media";

// Genre, per category.
//
// A fixed list rather than a free-text field, and that is the entire
// point of the feature. Typed genres arrive as "Hip-Hop", "hip hop",
// "HipHop" and "rap", which cannot be grouped, counted, filtered or
// recommended on - so a free-text genre is a genre you cannot use for
// anything, which is the same as not having one.
//
// Everything downstream that wants to know what somebody is into is
// currently stuck with three values: music, movie_tv, photography.
// "You like movies" is not a taste. This is the smallest field that
// turns it into one.
//
// Slugs are stored, labels are displayed. Renaming a label later then
// costs nothing, while renaming a stored value costs a migration.

/**
 * A genre is a slug in a family.
 *
 * The list used to be flat: sixty-three for music, forty-four for film,
 * thirty-two for photography. That is enough to say what something
 * broadly is and not nearly enough to find anything, which is the only
 * reason the field exists - "you like electronic" is barely more of a
 * taste than "you like music". Eight hundred, in families, is a taxonomy
 * somebody can actually dig through.
 *
 * The family layer is what makes that size usable rather than a wall.
 * Nobody scrolls three hundred and sixty-nine music genres; they know
 * they want something electronic and then they want to see what is under
 * it. So the picker can group, the search can rank within a family, and
 * a shelf can say what neighbourhood a microgenre sits in.
 *
 * Every slug that was in the old flat list is still here, in a family.
 * Removing one would not delete the posts using it - it would make them
 * invisible: isGenreFor goes false, the badge stops rendering, and no
 * filter ever matches that row again. So "psychedelic" lives alongside
 * "psychedelic-rock" and "synthpop" alongside "synth-pop", which is
 * untidy and correct.
 */
export type GenreFamily = {
  slug: string;
  label: string;
  genres: readonly string[];
};

export const FAMILIES: Record<MediaType, readonly GenreFamily[]> = {
  music: [
    {
      slug: "rock",
      label: "Rock",
      genres: [
        "rock",
        "classic-rock",
        "hard-rock",
        "soft-rock",
        "psychedelic-rock",
        "psychedelic",
        "indie",
        "prog",
        "garage-rock",
        "surf-rock",
        "glam-rock",
        "southern-rock",
        "blues-rock",
        "folk-rock",
        "art-rock",
        "krautrock",
        "stoner-rock",
        "math-rock",
        "noise-rock",
        "space-rock",
        "jam-band",
        "grunge",
        "britpop",
        "indie-rock",
        "alternative",
        "post-rock",
        "slowcore",
        "sadcore",
        "emo",
        "midwest-emo",
        "screamo",
        "shoegaze",
        "dream-pop",
        "jangle-pop",
        "power-pop",
        "new-wave",
        "post-punk",
        "no-wave",
        "coldwave",
        "darkwave",
      ],
    },
    {
      slug: "metal",
      label: "Metal",
      genres: [
        "metal",
        "heavy-metal",
        "thrash",
        "death-metal",
        "black-metal",
        "doom-metal",
        "sludge",
        "stoner-metal",
        "power-metal",
        "speed-metal",
        "nu-metal",
        "metalcore",
        "deathcore",
        "grindcore",
        "progressive-metal",
        "symphonic-metal",
        "folk-metal",
        "industrial-metal",
        "djent",
        "post-metal",
        "blackgaze",
        "drone-metal",
      ],
    },
    {
      slug: "punk",
      label: "Punk",
      genres: [
        "punk",
        "hardcore-punk",
        "hardcore",
        "post-hardcore",
        "pop-punk",
        "skate-punk",
        "oi",
        "anarcho-punk",
        "crust-punk",
        "d-beat",
        "riot-grrrl",
        "queercore",
        "ska-punk",
        "horror-punk",
        "proto-punk",
      ],
    },
    {
      slug: "pop",
      label: "Pop",
      genres: [
        "pop",
        "synth-pop",
        "synthpop",
        "electropop",
        "dance-pop",
        "teen-pop",
        "bubblegum",
        "art-pop",
        "hyperpop",
        "bedroom-pop",
        "chamber-pop",
        "baroque-pop",
        "sophisti-pop",
        "city-pop",
        "kpop",
        "jpop",
        "cpop",
        "europop",
        "schlager",
        "yacht-rock",
        "new-romantic",
      ],
    },
    {
      slug: "hip-hop",
      label: "Hip-Hop",
      genres: [
        "hip-hop",
        "boom-bap",
        "east-coast",
        "west-coast",
        "g-funk",
        "dirty-south",
        "trap",
        "drill",
        "uk-drill",
        "plugg",
        "rage",
        "cloud-rap",
        "phonk",
        "memphis-rap",
        "horrorcore",
        "conscious-hip-hop",
        "jazz-rap",
        "abstract-hip-hop",
        "underground-hip-hop",
        "alternative-hip-hop",
        "crunk",
        "snap",
        "hyphy",
        "bounce",
        "miami-bass",
        "chopped-and-screwed",
        "grime",
        "uk-hip-hop",
        "afroswing",
        "emo-rap",
        "mumble-rap",
        "battle-rap",
        "turntablism",
      ],
    },
    {
      slug: "rnb",
      label: "R&B and Soul",
      genres: [
        "rnb",
        "soul",
        "neo-soul",
        "northern-soul",
        "southern-soul",
        "motown",
        "philly-soul",
        "quiet-storm",
        "new-jack-swing",
        "contemporary-rnb",
        "alternative-rnb",
        "pbrnb",
        "funk",
        "p-funk",
        "boogie",
        "disco",
        "nu-disco",
        "gospel",
        "doo-wop",
        "blue-eyed-soul",
      ],
    },
    {
      slug: "electronic",
      label: "Electronic",
      genres: [
        "electronic",
        "house",
        "deep-house",
        "tech-house",
        "acid-house",
        "progressive-house",
        "french-house",
        "garage-house",
        "afro-house",
        "amapiano",
        "techno",
        "detroit-techno",
        "minimal-techno",
        "acid-techno",
        "hard-techno",
        "electro",
        "idm",
        "glitch",
        "breakbeat",
        "big-beat",
        "breakcore",
        "jungle",
        "drum-and-bass",
        "liquid-dnb",
        "neurofunk",
        "footwork",
        "juke",
        "uk-garage",
        "garage",
        "2-step",
        "speed-garage",
        "bassline",
        "dubstep",
        "brostep",
        "future-garage",
        "trance",
        "psytrance",
        "goa",
        "hardstyle",
        "gabber",
        "happy-hardcore",
        "synthwave",
        "vaporwave",
        "chillwave",
        "witch-house",
        "edm",
        "future-bass",
        "trip-hop",
        "downtempo",
        "chillout",
        "lo-fi",
        "electroclash",
        "ebm",
        "industrial",
        "synth-punk",
        "chiptune",
      ],
    },
    {
      slug: "ambient",
      label: "Ambient and Drone",
      genres: [
        "ambient",
        "dark-ambient",
        "drone",
        "new-age",
        "field-recording",
        "musique-concrete",
        "lowercase",
        "isolationism",
        "space-ambient",
        "healing",
      ],
    },
    {
      slug: "jazz",
      label: "Jazz",
      genres: [
        "jazz",
        "bebop",
        "hard-bop",
        "cool-jazz",
        "modal-jazz",
        "free-jazz",
        "avant-garde-jazz",
        "spiritual-jazz",
        "jazz-fusion",
        "smooth-jazz",
        "swing",
        "big-band",
        "dixieland",
        "ragtime",
        "latin-jazz",
        "nu-jazz",
        "acid-jazz",
        "vocal-jazz",
        "third-stream",
      ],
    },
    {
      slug: "blues",
      label: "Blues",
      genres: [
        "blues",
        "delta-blues",
        "chicago-blues",
        "electric-blues",
        "country-blues",
        "piedmont-blues",
        "jump-blues",
        "boogie-woogie",
        "hill-country-blues",
      ],
    },
    {
      slug: "folk",
      label: "Folk and Country",
      genres: [
        "folk",
        "singer-songwriter",
        "americana",
        "alt-country",
        "country",
        "outlaw-country",
        "bluegrass",
        "old-time",
        "honky-tonk",
        "country-pop",
        "western-swing",
        "cowpunk",
        "freak-folk",
        "anti-folk",
        "celtic",
        "sea-shanty",
        "protest-song",
        "appalachian",
        "gospel-country",
        "bakersfield",
      ],
    },
    {
      slug: "classical",
      label: "Classical",
      genres: [
        "classical",
        "baroque",
        "romantic",
        "impressionist",
        "modernist",
        "minimalism",
        "opera",
        "chamber-music",
        "orchestral",
        "choral",
        "early-music",
        "contemporary-classical",
        "neoclassical",
        "serialism",
        "piano-solo",
        "string-quartet",
        "requiem",
        "soundtrack",
        "score",
        "musical-theatre",
      ],
    },
    {
      slug: "latin",
      label: "Latin",
      genres: [
        "latin",
        "salsa",
        "bachata",
        "merengue",
        "cumbia",
        "reggaeton",
        "latin-trap",
        "bossa-nova",
        "samba",
        "mpb",
        "tropicalia",
        "tango",
        "flamenco",
        "ranchera",
        "mariachi",
        "norteno",
        "banda",
        "corridos",
        "vallenato",
        "bolero",
        "son-cubano",
        "timba",
        "chicha",
      ],
    },
    {
      slug: "caribbean",
      label: "Caribbean",
      genres: [
        "reggae",
        "roots-reggae",
        "dub",
        "dancehall",
        "ska",
        "rocksteady",
        "soca",
        "calypso",
        "zouk",
        "kompa",
        "bouyon",
        "reggae-fusion",
      ],
    },
    {
      slug: "african",
      label: "African",
      genres: [
        "afrobeats",
        "afrobeat",
        "highlife",
        "juju",
        "soukous",
        "mbalax",
        "kwaito",
        "gqom",
        "bongo-flava",
        "ethio-jazz",
        "desert-blues",
        "tuareg",
        "gnawa",
        "rai",
        "coupe-decale",
        "amapiano-vocal",
        "azonto",
      ],
    },
    {
      slug: "asian",
      label: "Asian and Global",
      genres: [
        "bollywood",
        "filmi",
        "bhangra",
        "hindustani",
        "carnatic",
        "ghazal",
        "qawwali",
        "gamelan",
        "enka",
        "city-pop-jp",
        "mandopop",
        "cantopop",
        "thai-pop",
        "dangdut",
        "luk-thung",
        "turkish-psych",
        "arabesque",
        "klezmer",
        "balkan-brass",
        "fado",
        "chanson",
        "folk-revival",
      ],
    },
    {
      slug: "experimental",
      label: "Experimental",
      genres: [
        "experimental",
        "noise",
        "harsh-noise",
        "power-electronics",
        "avant-garde",
        "free-improvisation",
        "sound-collage",
        "plunderphonics",
        "turntable-music",
        "microtonal",
        "spoken-word",
        "sound-art",
        "electroacoustic",
        "tape-music",
        "onkyo",
      ],
    },
  ],
  movie_tv: [
    {
      slug: "drama",
      label: "Drama",
      genres: [
        "drama",
        "melodrama",
        "period-drama",
        "historical",
        "biopic",
        "courtroom",
        "medical-drama",
        "political-drama",
        "social-realism",
        "kitchen-sink",
        "coming-of-age",
        "family-drama",
        "family",
        "musical",
        "sports",
        "psychological-drama",
        "tragedy",
        "epic",
        "war",
        "anti-war",
        "prison",
        "sports-drama",
        "addiction",
        "road-movie",
      ],
    },
    {
      slug: "comedy",
      label: "Comedy",
      genres: [
        "comedy",
        "romantic-comedy",
        "screwball",
        "slapstick",
        "satire",
        "parody",
        "spoof",
        "dark-comedy",
        "black-comedy",
        "mockumentary",
        "cringe-comedy",
        "buddy-comedy",
        "stoner-comedy",
        "teen-comedy",
        "workplace-comedy",
        "sitcom",
        "sketch",
        "stand-up",
        "improv",
        "farce",
      ],
    },
    {
      slug: "action",
      label: "Action",
      genres: [
        "action",
        "action-comedy",
        "martial-arts",
        "kung-fu",
        "wuxia",
        "samurai",
        "heist",
        "spy",
        "espionage",
        "car-chase",
        "disaster",
        "survival",
        "adventure",
        "western",
        "swashbuckler",
        "superhero",
        "kaiju",
        "military",
        "revenge",
        "one-location",
      ],
    },
    {
      slug: "horror",
      label: "Horror",
      genres: [
        "horror",
        "slasher",
        "supernatural-horror",
        "psychological-horror",
        "body-horror",
        "folk-horror",
        "cosmic-horror",
        "found-footage",
        "creature-feature",
        "zombie",
        "vampire",
        "werewolf",
        "haunted-house",
        "possession",
        "occult",
        "giallo",
        "splatter",
        "gothic-horror",
        "home-invasion",
        "monster-movie",
        "elevated-horror",
        "camp-horror",
      ],
    },
    {
      slug: "thriller",
      label: "Thriller",
      genres: [
        "thriller",
        "psychological-thriller",
        "psychological",
        "conspiracy",
        "techno-thriller",
        "erotic-thriller",
        "legal-thriller",
        "paranoid-thriller",
        "neo-noir",
        "noir",
        "mystery",
        "whodunit",
        "detective",
        "procedural",
        "cat-and-mouse",
        "hitchcockian",
      ],
    },
    {
      slug: "scifi",
      label: "Science Fiction",
      genres: [
        "sci-fi",
        "hard-sci-fi",
        "space-opera",
        "cyberpunk",
        "dystopian",
        "post-apocalyptic",
        "time-travel",
        "alien-invasion",
        "first-contact",
        "artificial-intelligence",
        "biopunk",
        "steampunk",
        "solarpunk",
        "climate-fiction",
        "simulation",
        "body-snatcher",
        "retro-futurism",
      ],
    },
    {
      slug: "fantasy",
      label: "Fantasy",
      genres: [
        "fantasy",
        "high-fantasy",
        "dark-fantasy",
        "urban-fantasy",
        "fairy-tale",
        "sword-and-sorcery",
        "magical-realism",
        "mythology",
        "portal-fantasy",
        "fable",
      ],
    },
    {
      slug: "romance",
      label: "Romance",
      genres: [
        "romance",
        "romantic-drama",
        "tragic-romance",
        "queer-romance",
        "period-romance",
        "workplace-romance",
        "second-chance",
        "slow-burn",
        "love-triangle",
      ],
    },
    {
      slug: "crime",
      label: "Crime",
      genres: [
        "crime",
        "gangster",
        "mafia",
        "yakuza",
        "true-crime",
        "caper",
        "con-artist",
        "serial-killer",
        "police",
        "organised-crime",
        "heist-thriller",
        "prison-break",
        "cartel",
      ],
    },
    {
      slug: "documentary",
      label: "Documentary",
      genres: [
        "documentary",
        "nature-doc",
        "music-doc",
        "sports-doc",
        "true-crime-doc",
        "political-doc",
        "essay-film",
        "cinema-verite",
        "direct-cinema",
        "archival",
        "concert-film",
        "travelogue",
        "investigative",
        "biographical-doc",
        "food-doc",
      ],
    },
    {
      slug: "animation",
      label: "Animation",
      genres: [
        "animation",
        "anime",
        "shonen",
        "shojo",
        "seinen",
        "isekai",
        "mecha",
        "slice-of-life",
        "stop-motion",
        "claymation",
        "cut-out",
        "rotoscope",
        "cgi-animation",
        "hand-drawn",
        "adult-animation",
        "cartoon",
        "short-film-animation",
      ],
    },
    {
      slug: "tv",
      label: "Television",
      genres: [
        "miniseries",
        "limited-series",
        "anthology",
        "soap",
        "telenovela",
        "game-show",
        "reality",
        "competition",
        "dating-show",
        "talk-show",
        "variety",
        "late-night",
        "docuseries",
        "procedural-tv",
        "serialised-drama",
        "web-series",
        "kids-tv",
      ],
    },
    {
      slug: "shelf",
      label: "On the Shelf",
      genres: [
        "cult",
        "midnight-movie",
        "b-movie",
        "grindhouse",
        "exploitation",
        "blaxploitation",
        "arthouse",
        "new-wave-cinema",
        "french-new-wave",
        "italian-neorealism",
        "dogme",
        "mumblecore",
        "slow-cinema",
        "experimental-film",
        "experimental",
        "short",
        "silent",
        "pre-code",
        "technicolor",
        "director-cut",
        "criterion",
        "a24",
        "studio-ghibli",
        "hammer-horror",
        "hong-kong-cinema",
        "nollywood",
        "comfort-watch",
        "feel-good",
        "tearjerker",
        "rewatchable",
        "one-sitting",
        "turn-your-brain-off",
        "under-90-minutes",
        "three-hours-plus",
        "holiday",
        "christmas",
        "halloween",
        "summer-blockbuster",
        "awards-bait",
        "box-office-bomb",
        "so-bad-its-good",
        "guilty-pleasure",
        "childhood-favourite",
        "banned",
        "lost-media",
        "remake",
        "reboot",
        "sequel",
        "prequel",
        "adaptation",
        "based-on-a-book",
        "based-on-a-true-story",
        "directorial-debut",
        "ensemble-cast",
        "one-take",
        "black-and-white-film",
        "foreign-language",
        "subtitled",
      ],
    },
  ],
  photography: [
    {
      slug: "people",
      label: "People",
      genres: [
        "portrait",
        "self-portrait",
        "environmental-portrait",
        "studio-portrait",
        "candid",
        "group-portrait",
        "family",
        "wedding",
        "engagement",
        "maternity",
        "newborn",
        "boudoir",
        "headshot",
        "fashion",
        "editorial-fashion",
        "beauty",
        "glamour",
        "nude",
        "figure-study",
        "dance",
        "performance",
        "backstage",
      ],
    },
    {
      slug: "place",
      label: "Place",
      genres: [
        "landscape",
        "seascape",
        "cityscape",
        "architecture",
        "interior",
        "urban",
        "rural",
        "industrial",
        "urbex",
        "aerial",
        "drone",
        "travel",
        "documentary-travel",
        "night",
        "astro",
        "cloudscape",
        "desert",
        "mountain",
        "forest",
        "coastal",
        "road",
      ],
    },
    {
      slug: "nature",
      label: "Nature",
      genres: [
        "nature",
        "wildlife",
        "birds",
        "macro",
        "insects",
        "botanical",
        "flowers",
        "underwater",
        "marine",
        "pets",
        "animals",
        "weather",
        "storm",
        "seasons",
        "conservation",
      ],
    },
    {
      slug: "street",
      label: "Street and Documentary",
      genres: [
        "street",
        "documentary",
        "photojournalism",
        "reportage",
        "war-photography",
        "protest",
        "social-documentary",
        "ethnographic",
        "daily-life",
        "subculture",
        "festival",
        "market",
        "transit",
        "found-people",
      ],
    },
    {
      slug: "studio",
      label: "Studio and Commercial",
      genres: [
        "still-life",
        "product",
        "food",
        "tabletop",
        "advertising",
        "editorial",
        "catalogue",
        "architectural-interiors",
        "real-estate",
        "corporate",
        "stock",
        "packshot",
        "flat-lay",
        "levitation",
      ],
    },
    {
      slug: "sport",
      label: "Sport and Action",
      genres: [
        "sport",
        "motorsport",
        "surf",
        "skate",
        "climbing",
        "cycling",
        "running",
        "water-sport",
        "winter-sport",
        "action-sport",
        "equestrian",
      ],
    },
    {
      slug: "process",
      label: "Process and Technique",
      genres: [
        "long-exposure",
        "double-exposure",
        "multiple-exposure",
        "light-painting",
        "panning",
        "bokeh",
        "hdr",
        "panorama",
        "time-lapse",
        "focus-stacking",
        "tilt-shift",
        "infrared",
        "ultraviolet",
        "high-speed",
        "strobe",
        "available-light",
        "natural-light",
        "golden-hour",
        "blue-hour",
        "backlit",
        "silhouette",
        "reflection",
        "shadow-play",
      ],
    },
    {
      slug: "analogue",
      label: "Analogue and Alt-Process",
      genres: [
        "analogue",
        "film",
        "35mm",
        "medium-format",
        "large-format",
        "polaroid",
        "instant",
        "slide-film",
        "black-and-white",
        "darkroom",
        "cyanotype",
        "tintype",
        "wet-plate",
        "daguerreotype",
        "platinum-print",
        "gum-bichromate",
        "pinhole",
        "lomography",
        "expired-film",
        "cross-process",
        "push-process",
        "redscale",
        "half-frame",
        "disposable",
      ],
    },
    {
      slug: "style",
      label: "Style and Movement",
      genres: [
        "fine-art",
        "abstract",
        "minimalist",
        "minimal",
        "conceptual",
        "surreal",
        "staged",
        "tableau",
        "collage",
        "photomontage",
        "composite",
        "cinematic",
        "vernacular",
        "snapshot",
        "new-topographics",
        "straight-photography",
        "pictorialism",
        "dada-photo",
        "deadpan",
        "typology",
        "diptych",
        "series",
        "zine",
      ],
    },
    {
      slug: "digital",
      label: "Digital and New",
      genres: [
        "digital",
        "mobile",
        "smartphone",
        "360",
        "vr-photo",
        "3d-photo",
        "photogrammetry",
        "ai-assisted",
        "screenshot",
        "webcam",
        "cctv",
        "satellite",
        "scanner-art",
        "glitch-photo",
      ],
    },
  ],
};

/**
 * Every genre for a category, flat, in family order.
 *
 * Derived rather than written out, so the taxonomy is stated once. This
 * is what isGenreFor, mediaTypeForGenre and the search read, all of
 * which want a flat list and none of which should have to know about
 * families.
 */
export const GENRES: Record<MediaType, readonly string[]> = {
  music: FAMILIES.music.flatMap((f) => f.genres),
  movie_tv: FAMILIES.movie_tv.flatMap((f) => f.genres),
  photography: FAMILIES.photography.flatMap((f) => f.genres),
};

/** The family a genre sits in, so a picker can group and a badge can say. */
export function familyForGenre(mediaType: MediaType, slug: string): GenreFamily | null {
  return FAMILIES[mediaType].find((f) => f.genres.includes(slug)) ?? null;
}

export const COMMON_GENRES: Record<MediaType, readonly string[]> = {
  music: ["pop", "hip-hop", "rnb", "rock", "indie", "electronic", "jazz", "metal"],
  movie_tv: ["action", "comedy", "drama", "horror", "thriller", "sci-fi", "documentary", "anime"],
  photography: ["portrait", "street", "landscape", "nature", "fashion", "film", "documentary"],
};

/**
 * What people type when they mean something else.
 *
 * This is the whole difference between a search box that works and one
 * that makes you guess the site's vocabulary. Nobody searches "hip-hop"
 * - they type "rap". Nobody types "rnb". A picker that answers "no
 * matches" to "rap" has told a lie about what it contains.
 */
const ALIASES: Record<string, readonly string[]> = {
  "hip-hop": ["rap", "hiphop"],
  rnb: ["r&b", "rhythm and blues", "randb"],
  kpop: ["k-pop", "korean"],
  jpop: ["j-pop", "japanese"],
  "sci-fi": ["scifi", "science fiction"],
  "drum-and-bass": ["dnb", "drum n bass", "jungle"],
  electronic: ["edm", "dance", "electronica"],
  "stand-up": ["standup", "comedy special"],
  "coming-of-age": ["coming of age", "teen"],
  "black-and-white": ["b&w", "bw", "monochrome", "mono"],
  analogue: ["analog", "35mm", "film camera"],
  "musical-theatre": ["musical theater", "showtunes", "broadway"],
  soundtrack: ["score", "ost"],
  documentary: ["doc", "docs"],
  "true-crime": ["true crime"],
  psychedelic: ["psych"],
  prog: ["progressive"],
  "lo-fi": ["lofi"],
  "still-life": ["still life"],
  "self-portrait": ["selfie", "self portrait"],
  "fine-art": ["fine art", "art"],
  astro: ["astrophotography", "stars", "night sky"],
  photojournalism: ["photojournalist", "news"],
  "found-footage": ["found footage"],
  "martial-arts": ["martial arts", "kung fu"],
  "nature-doc": ["nature documentary", "wildlife doc"],
  "road-movie": ["road movie", "road trip"],
  "field-recording": ["field recording", "sound art"],
  "bossa-nova": ["bossa"],
  "new-wave": ["newwave"],
  "dream-pop": ["dreampop"],
  "post-punk": ["postpunk"],
  "bedroom-pop": ["bedroom"],
  "city-pop": ["citypop"],
  "singer-songwriter": ["singer songwriter", "acoustic"],
};

/** Loosened for matching: lowercase, punctuation spaced, runs collapsed. */
function loosen(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Genres matching what somebody typed.
 *
 * Prefix matches first, then anything containing it. "pop" should offer
 * Pop before Bedroom Pop and Dream Pop, because the exact thing you
 * typed being third in its own result list is the most annoying
 * behaviour a search box has.
 */
export function searchGenres(mediaType: MediaType, query: string, limit = 12): string[] {
  const q = loosen(query);
  const all = GENRES[mediaType] as readonly string[];
  if (!q) return [...COMMON_GENRES[mediaType]];

  const starts: string[] = [];
  const contains: string[] = [];
  for (const slug of all) {
    const terms = [genreLabel(slug), slug, ...(ALIASES[slug] ?? [])].map(loosen);
    if (terms.some((t) => t.startsWith(q))) starts.push(slug);
    else if (terms.some((t) => t.includes(q))) contains.push(slug);
  }
  return [...starts, ...contains].slice(0, limit);
}

// Only where the slug and the label differ. Everything else is title-cased
// from the slug, so adding a genre above usually needs nothing here.
const LABEL_OVERRIDES: Record<string, string> = {
  "hip-hop": "Hip-Hop",
  rnb: "R&B",
  kpop: "K-Pop",
  jpop: "J-Pop",
  "sci-fi": "Sci-Fi",
  rock: "Rock",
  "drum-and-bass": "Drum & Bass",
  "lo-fi": "Lo-Fi",
  prog: "Prog Rock",
  "black-and-white": "Black & White",
  "musical-theatre": "Musical Theatre",
  "stand-up": "Stand-Up",
  "coming-of-age": "Coming-of-Age",
  "post-punk": "Post-Punk",
  "new-wave": "New Wave",
  "dream-pop": "Dream Pop",
  "city-pop": "City Pop",
  "bedroom-pop": "Bedroom Pop",
  "bossa-nova": "Bossa Nova",
  "self-portrait": "Self-Portrait",
  "still-life": "Still Life",
  "fine-art": "Fine Art",
  "found-footage": "Found Footage",
  "martial-arts": "Martial Arts",
  "nature-doc": "Nature Doc",
  "true-crime": "True Crime",
  "road-movie": "Road Movie",
  "field-recording": "Field Recording",
  "singer-songwriter": "Singer-Songwriter",
  "double-exposure": "Double Exposure",
  "long-exposure": "Long Exposure",
  "game-show": "Game Show",
  // Initialisms and the like. Title-casing a slug is right for almost
  // everything and wrong for anything that is an abbreviation, a
  // measurement or a place: "Idm", "35mm" and "Uk Drill" all read as
  // mistakes, and a list of eight hundred has enough of them to notice.
  idm: "IDM",
  edm: "EDM",
  ebm: "EBM",
  mpb: "MPB",
  hdr: "HDR",
  cctv: "CCTV",
  oi: "Oi!",
  pbrnb: "PBR&B",
  "uk-drill": "UK Drill",
  "uk-garage": "UK Garage",
  "uk-hip-hop": "UK Hip-Hop",
  "contemporary-rnb": "Contemporary R&B",
  "alternative-rnb": "Alternative R&B",
  "liquid-dnb": "Liquid D&B",
  "city-pop-jp": "City Pop (Japan)",
  "cgi-animation": "CGI Animation",
  "35mm": "35mm",
  "360": "360",
  "vr-photo": "VR Photo",
  "3d-photo": "3D Photo",
  "ai-assisted": "AI Assisted",
  "2-step": "2-Step",
  "d-beat": "D-Beat",
  "p-funk": "P-Funk",
  "g-funk": "G-Funk",
  "a24": "A24",
  "so-bad-its-good": "So Bad It's Good",
  "turn-your-brain-off": "Turn Your Brain Off",
  "under-90-minutes": "Under 90 Minutes",
  "three-hours-plus": "Three Hours Plus",
  "based-on-a-book": "Based on a Book",
  "based-on-a-true-story": "Based on a True Story",
  "one-take": "One Take",
  "director-cut": "Director's Cut",
  "coupe-decale": "Coupé-Décalé",
  tropicalia: "Tropicália",
  "son-cubano": "Son Cubano",
  "cinema-verite": "Cinéma Vérité",
  "french-new-wave": "French New Wave",
  "studio-ghibli": "Studio Ghibli",
  "hong-kong-cinema": "Hong Kong Cinema",
  "black-and-white-film": "Black & White",
  "new-topographics": "New Topographics",
};

export function genreLabel(slug: string): string {
  return (
    LABEL_OVERRIDES[slug] ??
    slug
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" ")
  );
}

/**
 * Whether this genre belongs to this category.
 *
 * Checked as a pair, always. "Documentary" is a genre of both film and
 * photography but not of music, and a post claiming a genre its category
 * doesn't have is a row that no filter will ever match - invisible, and
 * so never reported.
 */
export function isGenreFor(mediaType: MediaType, value: unknown): value is string {
  return typeof value === "string" && (GENRES[mediaType] as readonly string[]).includes(value);
}

/** Which category a genre belongs to, for building a link out of a badge. */
export function mediaTypeForGenre(slug: string): MediaType | null {
  for (const [type, list] of Object.entries(GENRES)) {
    if ((list as readonly string[]).includes(slug)) return type as MediaType;
  }
  return null;
}
